version: '3'

services:
  server1:
    image: php:7.4-apache
    container_name: server1
    volumes:
      - ./server1:/var/www/html
    networks:
      - lb-net

  server2:
    image: php:7.4-apache
    container_name: server2
    volumes:
      - ./server2:/var/www/html
    networks:
      - lb-net

  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    volumes:
      - ./nginx-lb/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
    networks:
      - lb-net

networks:
  lb-net:
    driver: bridge
